### ISSUE TITLE
Lagging Graph Point Dragging

### ISSUE THREAD

**Issue by clary149** [Doenet/DoenetTools#1297]
From Lucia at the conference:

I'm getting slower, jumpy performance for dragging the point after I uncomment the first chunk of lines for making a graph: 
```
<!--  <graph>
  <function> -x^2 </function>
  <parabola name ="parab" stylenumber="2" label="p" applyStyleToLabel/>
</graph>   -->

<p> Move the point to the first quadrant.</p>
<graph> <point name="Poi"> (-3,-4)</point> </graph>

 <answer>
  <award targetsAreResponses="Poi">
    <when> <copy prop="x" target="Poi" /> > 0 and <copy prop="y" target="Poi" /> > 0 </when>
  </award> 
</answer>  
```

**Comment by dqnykamp** [comment]
Below is a more extreme example, as it plots 30 functions on top of each other.

Because an answer credit depends on point Poi, and because the document credit achieved depends on the answer, moving point Poi invokes a call to update the document renderer.  (This update call to document is due to the creditAchieved of a document is flagged "forRenderer" due to the possibility of a document-wide checkwork button.)

The bad, and hopefully unnecessary, part, is that the call to updating the document renderer is giving a call to update the renderers of all the functions.  Further confirmation that the renderers are the problem and not core, is that adding hide="true" to the graph eliminates the lag.

@kevincharles  What are we doing wrong with the recoil setup that is making all these functions update when nothing is affecting them?


```
<graph>
  <function>x^2</function>
  <function>x^2</function>
  <function>x^2</function>
  <function>x^2</function>
  <function>x^2</function>
  <function>x^2</function>
  <function>x^2</function>
  <function>x^2</function>
  <function>x^2</function>
  <function>x^2</function>
  <function>x^2</function>
  <function>x^2</function>
  <function>x^2</function>
  <function>x^2</function>
  <function>x^2</function>
  <function>x^2</function>
  <function>x^2</function>
  <function>x^2</function>
  <function>x^2</function>
  <function>x^2</function>
  <function>x^2</function>
  <function>x^2</function>
  <function>x^2</function>
  <function>x^2</function>
  <function>x^2</function>
  <function>x^2</function>
  <function>x^2</function>
  <function>x^2</function>
  <function>x^2</function>
  <function>x^2</function>
</graph>

<p> Move the point to the first quadrant.</p>
<graph> <point name="Poi"> (-3,-4)</point> </graph>
 <answer>
  <award targetsAreResponses="Poi">
    <when> <copy prop="x" target="Poi" /> > 0 and <copy prop="y" target="Poi" /> > 0 </when>
  </award> 
</answer> 
```

**Comment by dqnykamp** [comment]
#1306 fixes this and makes great speed improvements
