### ISSUE TITLE
styling change - enlarge all marker sizes (for points) and make all a consistent size

### ISSUE THREAD

**Issue by virginiaMae** [Doenet/DoenetTools#1753]
styling change for points and endpoints on a graph: per meeting 10/21, change all marker sizes to one size; this size should be at least larger than the default size for styleNumber #1

**Comment by dqnykamp** [comment]
FYI: these sizes are defined in https://github.com/Doenet/DoenetTools/blob/main/src/Core/utils/style.js

**Comment by keaganeng** [comment]
Is there a location where the "diamond" and "triangle" points have their size defined (either explicitly or via a function)? The `markerSize` attribute in [style.js](https://github.com/Doenet/DoenetTools/blob/main/src/Core/utils/style.js) does not affect either of the points.

**Comment by dqnykamp** [comment]
JSXGraph is determined to plot triangles and diamonds smaller!  `markerSize` does affect them, but it's on a different scale.  Just playing around, it seems like you have multiply markerSize by 1.5 for triangle and 1.4 for diamonds to get the shapes to be approximately the same size.
![image](https://user-images.githubusercontent.com/1037056/199610986-828b86bc-db15-49a7-86c7-856609f9b98e.png)

I'm wondering if we should just have the [point.jsx](https://github.com/Doenet/DoenetTools/blob/main/src/Viewer/renderers/point.jsx) renderer multiply markerSize by these factors so that a markerSize of 5 in DoenetML looks approximately the same for all these shapes.  Alternativelty, we could just increase the default sizes in style.js.  I'm leaning toward making a `markerSize="5"` in DoenetML give approximately the same size.

@virginiaMae, do you have an opinion?

**Comment by virginiaMae** [comment]
I agree with keeping it a uniform markerSize = 5 attribute in Doenet with a behind-the-scenes adjustment so that they all look the same.
