### ISSUE TITLE
angle component styling not working

### ISSUE THREAD

**Issue by virginiaMae** [Doenet/DoenetTools#1773]
Currently, it is not possible to change the color of the angle shown when using the <angle> component. The styleNumber attribute is allowed but has no effect.

**Comment by dqnykamp** [comment]
The angle renderer currently has this hard coded:
```
   let angleColor = getComputedStyle(document.documentElement).getPropertyValue("--solidLightBlue");
```
I'm not sure what style attributes we should use to control the angle styling.  fillColor and fillOpacity probably aren't good ones, as all default styles have fillColor="none", so that polygons, circles, etc., are unfilled.  The angle, however, should be filled by default.

We could use the lineColor attribute or make up new attributes, like angleColor and angleOpacity.

**Comment by dqnykamp** [comment]
Another possibility is to change how we use `fillColor`.  We could always have it set to a color (rather than the current default of "none"), but then add a boolean attribute, such as `filled`.  If `filled` is false, we ignore `fillColor` in polygons, circles, etc.  If `filled` is true, then we use `fillColor` for polygons, circles, etc.

The advantage of this change would be that we could use `fillColor` for the angle (making angle ignore the `filled` attribute, i.e., assuming that an angle must always be filled).

Would the addition of such a `filled` attribute be confusing since I don't think other systems work that way?

**Comment by virginiaMae** [comment]
I like this latest idea of adding the "filled" attribute. I don't find it confusing, and it would come in handy for polygons the author wants to show as filled, but doesn't want to add in a specific color. I think that the expected behavior in this case would be that 
&lt;rectangle styleNumber="2" filled/&gt; would create a filled red rectangle
