### ISSUE TITLE
new attribute "filled" for geometric components

### ISSUE THREAD

**Issue by virginiaMae** [Doenet/DoenetTools#1883]
Add a way for authors to specify that a polygon, circle, triangle, rectangle, etc. is filled within the component. Suggest both a boolean input, which will match the current styleNumber of the component, and also including a way to specify the color of the fill as separate from the component's styleNumber, such as filled="red", which will produce a blue edged circle with a red fill  if the circle has styleNumber = 1.

**Comment by dqnykamp** [comment]
I'll make `filled` be an attribute on those components.  However, since our aspiration is to allow users to override styling like colors (and for authors to not be able to rely on them being a particular color), I think that the actual styling for the fill (such as color or, eventually, a hatched pattern) will need to remain in the style definition.  The idea is that a user should be able to override the styling for the fill to make the difference between styles be clearer to them.  My plan is to make `fill` be a boolean attribute which, if true, will use the fillColor, fillOpacity, and (eventually) fillPattern(?) from the corresponding style.
