### ISSUE TITLE
nested ordered lists should switch numbering scheme from numbers to letters for the inner list

### ISSUE THREAD

**Issue by virginiaMae** [Doenet/DoenetTools#1928]
Similar to standard document outlining conventions:
1. (parent list using numbers by default)
     a. (nested list using letters)
           i. (etc...)

**Comment by dqnykamp** [comment]
Should this be configurable or just always set to a particular pattern?  Maybe make the default be whatever you get in Pretext.

We should keep track of "level" in DoenetML (like we do for nested sections) so that an empty <ref> to a <li> could display the correctly formatted number/letter.  (It currently displays ???, so we should fix that or make a separate issue if we fix the numbering scheme but not the ???.)

**Comment by virginiaMae** [comment]
I think we should start by matching the PreTeXt schema as a default, and add in configurable features in the future. If I'm reading this correctly, the second issue is for empty list items. I agree that it should display the number and/or letter, but not the ???. It feels like it should be acceptable to have an empty list item that retains the default list formatting.

**Comment by dqnykamp** [comment]
My previous comment was broken because I forgot to escape the word `<ref>`, which means it didn't display.  I was referring to how an empty `<ref>` to an `<li>` displays as a ???.  An empty `<li>` should work fine.
