### ISSUE TITLE
allow copies inside a graph to respond via "triggerWhenObjectsClicked" attribute

### ISSUE THREAD

**Issue by virginiaMae** [Doenet/DoenetTools#2206]
to avoid possible source of confusion for authors

**Comment by dqnykamp** [comment]
Just to be clear, I believe you are talking about the case
```
<setup><point name="P" /></setup>
<graph>$P</graph>
<updateValue triggerWhenObjectsClicked="P" stuff />
```
We want the `<updateValue>` (or `<callAction>` or `<triggerSet>`)  to be triggered when one clicks the copy of the point P in the graph.

However, if the graph were instead `<graph>$P{assignNames="P2"}</graph>` or `<graph><point copySource="P" /></graph>`, then triggering off P wouldn't work anymore.  One would have to trigger off P2 or _point2, respectively.  I think triggering off P would still work with `<graph><copy source="P" /></graph>` because in this last case, the copied point isn't given another name.
