### ISSUE TITLE
requested latex symbol - \xmark  (workshop request)

### ISSUE THREAD

**Issue by virginiaMae** [Doenet/DoenetTools#2257]
See the quoted comment below. Apparently `<m>` does support the `\checkmark` but not the `\xmark`

```
<!-- *** 
        
Q - Can the \chi symbol below be changed to an actual xmark?
        
*** -->

        
          <p>   
            <md>
              <mrow>x+1 \amp=4</mrow>
              <mrow>1+1 \amp=4</mrow>
              <mrow>2 \amp=4 ~(\chi~False)</mrow>
            </md>
          </p>
```

**Comment by dqnykamp** [comment]
The `\checkmark` command appears to be part of the amssymb Latex package, which is why it is supported by MathJax.  A quick search for a latex `\xmark` didn't match anything other than user-defined solutions, which would explain why MathJax does not support it.  Unless I missed something, it appears the only way to get `\xmark` to work is through a user-defined Latex command, but we haven't added support for that.

**Comment by dqnykamp** [comment]
I'm closing this issue, as we don't currently have plans to add support for user-defined Latex commands.
