### ISSUE TITLE
<numberList> should take a <math/> list as a child

### ISSUE THREAD

**Issue by virginiaMae** [Doenet/DoenetTools#2265]
Currently, in order to define a user-input sequence from a mathInput as a numberList, you must first define a separate mathList from it,

**Comment by dqnykamp** [comment]
The request is to make `<numberlistt><math>1,2,3</math></numberlist>` work for making the numberlist 1,2,3.  It currently gives NaN.

A workaround is to add an intervening `<mathList>`, i.e, this works:  `<numberlist><mathlist><math>1,2,3</math></mathlist></numberlist>`.

Currently, for a `<numberlist>`, all `<math>` children are adapted into `<number>`s (as it doesn't have any "math" child groups), so the logic can assume everything is already converted into numbers.  To implement this feature, we'd have to add a "math" child group so that `<math>` children are not adapted, and then manually convert them to numbers, adding the special case that if there is a single `<math>` child to look to see if it is a list of numbers.
